site_name: Hysteria 2
site_url: https://v2.hysteria.network/

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Light mode

  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - search.suggest
    - search.highlight

extra:
  generator: false
  social:
    - icon: fontawesome/solid/circle-dollar-to-slot
      link: https://nowpayments.io/donation?api_key=EJH83FM-FDC40ZW-QGDZRR4-A7SC67S
    - icon: fontawesome/brands/telegram
      link: https://t.me/hysteria_github
    - icon: fontawesome/brands/github
      link: https://github.com/apernet/hysteria

copyright: Copyright &copy; 2020 - 2023 The Hysteria Project

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/apernet/hysteria

plugins:
  - search
  - glightbox:
      skip_classes:
        - skip-lightbox
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          nav:
            - 首页: index.md
            - 文档:
                - 快速开始:
                    - 安装: docs/getting-started/Installation.md
                    - 服务端: docs/getting-started/Server.md
                    - 客户端: docs/getting-started/Client.md
                    - 第三方应用: docs/getting-started/3rd-party-apps.md
                - 进阶:
                    - 完整服务端配置: docs/advanced/Full-Server-Config.md
                    - 完整客户端配置: docs/advanced/Full-Client-Config.md
                    - ACL: docs/advanced/ACL.md
                    - 流量统计 API: docs/advanced/Traffic-Stats-API.md
                    - 透明代理: docs/advanced/TPROXY.md
                    - 端口跳跃: docs/advanced/Port-Hopping.md
                    - 日志: docs/advanced/Logging.md
                    - 性能优化: docs/advanced/Performance.md
                    - 故障排除: docs/advanced/Troubleshooting.md
                - 杂项:
                    - Hysteria 1/2 对比: docs/misc/2-vs-1.md
                    - 我不喜欢 YAML 怎么办？: docs/misc/Hate-YAML.md
                    - 关于 HTTP/3: docs/misc/About-HTTP3.md
                    - 可以套 CDN 吗？: docs/misc/CDN.md
                    - Hysteria 是多倍发包吗？: docs/misc/Hysteria-Brutal.md
                - 开发者:
                    - 构建: docs/developers/Build.md
                    - 协议: docs/developers/Protocol.md
                    - URI Scheme: docs/developers/URI-Scheme.md
            - 更新日志: docs/Changelog.md
            - GitHub: https://github.com/apernet/hysteria
            - TCP Brutal: https://github.com/apernet/tcp-brutal
            - 艺术创作: docs/Artworks.md
            - 捐赠: docs/Donation.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Docs:
      - Getting Started:
          - Installation: docs/getting-started/Installation.md
          - Server: docs/getting-started/Server.md
          - Client: docs/getting-started/Client.md
          - 3rd-party apps: docs/getting-started/3rd-party-apps.md
      - Advanced:
          - Full Server Config: docs/advanced/Full-Server-Config.md
          - Full Client Config: docs/advanced/Full-Client-Config.md
          - ACL: docs/advanced/ACL.md
          - Traffic Stats API: docs/advanced/Traffic-Stats-API.md
          - TProxy: docs/advanced/TPROXY.md
          - Port Hopping: docs/advanced/Port-Hopping.md
          - Logging: docs/advanced/Logging.md
          - Performance: docs/advanced/Performance.md
          - Troubleshooting: docs/advanced/Troubleshooting.md
      - Misc:
          - Hysteria 2 vs 1: docs/misc/2-vs-1.md
          - What if I hate YAML?: docs/misc/Hate-YAML.md
          - About HTTP/3: docs/misc/About-HTTP3.md
          - Can I use a CDN?: docs/misc/CDN.md
      - Developers:
          - Build: docs/developers/Build.md
          - Protocol: docs/developers/Protocol.md
          - URI Scheme: docs/developers/URI-Scheme.md
  - Changelog: docs/Changelog.md
  - GitHub: https://github.com/apernet/hysteria
  - TCP Brutal: https://github.com/apernet/tcp-brutal
  - Artworks: docs/Artworks.md
  - Donation: docs/Donation.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
